//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.17 at 11:59:38 AM IST 
//


package org.apache.nutch.namespace.page;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.apache.nutch.namespace.page package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Page_QNAME = new QName("http://www.example.org/page/", "Page");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.apache.nutch.namespace.page
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Page }
     * 
     */
    public Page createPage() {
        return new Page();
    }

    /**
     * Create an instance of {@link Reader }
     * 
     */
    public Reader createReader() {
        return new Reader();
    }

    /**
     * Create an instance of {@link Readers }
     * 
     */
    public Readers createReaders() {
        return new Readers();
    }

    /**
     * Create an instance of {@link Type }
     * 
     */
    public Type createType() {
        return new Type();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Page }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/page/", name = "Page")
    public JAXBElement<Page> createPage(Page value) {
        return new JAXBElement<Page>(_Page_QNAME, Page.class, null, value);
    }

}
